[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerBuildTarget = "prod"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
